markdown: rdiscount
pygments: true

name: Jonathan \"Duke\" Leto
email: jonathan@leto.net
location: Portland, OR

default_donation: 5
default_currency: USD
donation_url: http://leto.github.com/freeyourself

amazon_payments_account_id: 42

dwolla_account_id: 812-529-3608
dwolla_memo: Here is a donation for your valuable work.
dwolla_repeat_donation: 1

bitcoin_address: 15pwvXdXo8XxJbQhG41d9xtDmr2UoCXoPP

paypal_email: jaleto@gmail.com

google_merchant_id: 42

pledgie_campaign_id: 42
